const DB_KEY='reclora-test-accounts-v1';const SESSION_KEY='reclora-test-session-v1';
const read=()=>JSON.parse(localStorage.getItem(DB_KEY)||'{}');const write=v=>localStorage.setItem(DB_KEY,JSON.stringify(v));
const current=()=>{const s=localStorage.getItem(SESSION_KEY);return s?read()[s]:null};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function shell(content){document.querySelector('[data-account-app]').innerHTML=`<div class="reclora-brandbar"><a href="../"><img src="../logos/reclora/Reclora%20logo.png" alt="RecLora logo"><span>RecLora</span></a><a class="reclora-account-link" href="./">Test account home</a></div><main class="reclora-test-shell">${content}</main>`}
function notice(message,error=false){return `<div class="reclora-notice ${error?'reclora-error':''}">${esc(message)}</div>`}
function home(){const u=current();shell(`<section class="reclora-test-card"><span class="reclora-small">LOCAL TEST MODE</span><h1>RecLora accounts</h1><p>Create demo accounts for testing the mirrored site. These accounts live only in this browser and are not connected to Rec Room or any real service.</p>${u?`<div class="reclora-notice">Signed in as <strong>${esc(u.displayName)}</strong> (@${esc(u.username)})</div><p><a class="test-button" href="profile.html">Open test profile</a> <button class="test-button secondary" id="logout">Log out</button></p>`:`<p><a class="test-button" href="signup.html">Create test account</a> <a class="test-button secondary" href="login.html">Log in</a></p>`}</section><section class="reclora-test-card"><h2>What this does</h2><div class="reclora-test-grid"><div><strong>Signup</strong><p class="reclora-small">Creates a local demo identity with a display name and username.</p></div><div><strong>Login</strong><p class="reclora-small">Stores a local session so you can test account states.</p></div><div><strong>Profile</strong><p class="reclora-small">Edit your demo bio and avatar color without changing mirrored source pages.</p></div></div></section>`);document.querySelector('#logout')?.addEventListener('click',()=>{localStorage.removeItem(SESSION_KEY);location.reload()})}
function signup(){shell(`<section class="reclora-test-card"><span class="reclora-small">LOCAL TEST MODE</span><h1>Create account</h1><p>Use fake test data only. Nothing is sent to a server.</p><form id="signup"><label>Display name<input name="displayName" required maxlength="50" autocomplete="off"></label><label>Username<input name="username" required pattern="[A-Za-z0-9_.-]{3,24}" maxlength="24" autocomplete="off"></label><label>Test password<input name="password" type="password" required minlength="4" autocomplete="new-password"></label><button>Create test account</button></form><div id="msg"></div></section>`);document.querySelector('#signup').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target),username=String(f.get('username')).trim();const db=read();if(db[username]){document.querySelector('#msg').innerHTML=notice('That test username already exists.',true);return}db[username]={username,displayName:String(f.get('displayName')).trim(),password:String(f.get('password')),bio:'New RecLora test account',color:'#0b7f86'};write(db);localStorage.setItem(SESSION_KEY,username);location.href='profile.html'})}
function login(){shell(`<section class="reclora-test-card"><span class="reclora-small">LOCAL TEST MODE</span><h1>Log in</h1><form id="login"><label>Username<input name="username" required autocomplete="username"></label><label>Test password<input name="password" type="password" required autocomplete="current-password"></label><button>Log in</button></form><div id="msg"></div></section>`);document.querySelector('#login').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target),u=String(f.get('username')).trim(),db=read();if(!db[u]||db[u].password!==String(f.get('password'))){document.querySelector('#msg').innerHTML=notice('Test username or password is incorrect.',true);return}localStorage.setItem(SESSION_KEY,u);location.href='profile.html'})}
function profile(){const u=current();if(!u){location.href='login.html';return}shell(`<section class="reclora-test-card"><span class="reclora-small">LOCAL TEST PROFILE</span><h1>${esc(u.displayName)}</h1><p>@${esc(u.username)}</p><form id="profile"><label>Display name<input name="displayName" value="${esc(u.displayName)}" required></label><label>Bio<textarea name="bio" rows="4" style="width:100%;padding:.75rem;border:1px solid #c6d8d8;border-radius:10px;font:inherit">${esc(u.bio)}</textarea></label><label>Accent color<input name="color" type="color" value="${esc(u.color)}"></label><button>Save profile</button></form><div id="msg"></div></section>`);document.querySelector('#profile').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target),db=read();db[u.username]={...u,displayName:String(f.get('displayName')).trim(),bio:String(f.get('bio')).trim(),color:String(f.get('color'))};write(db);document.querySelector('#msg').innerHTML=notice('Profile saved in this browser.')})}
const mode=location.pathname.split('/').pop().replace('.html','')||'index';({index:home,signup,login,profile}[mode]||home)();
